apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "csv-processor.fullname" . }}-app
  labels:
    {{- include "csv-processor.labels" . | nindent 4 }}
data:
  AWS_REGION: {{ .Values.aws.region | quote }}
  S3_BUCKET: {{ required "aws.bucket must be set" .Values.aws.bucket | quote }}
  S3_PREFIX: {{ .Values.aws.prefix | quote }}
